### ISSUE TITLE
The #:port seems to be ignored

### ISSUE THREAD

**Issue by graywolf** [artyom-poptsov/guile-ssh#38]
Hello,

I am trying to deploy using guix deploy (which under the hood uses guile-ssh), and it seems the #:port argument to (make-session) is ignored.  I managed to reproduce it even without guix, the steps follow.

I have this in my ~/.ssh/config:

```
Host *.foo.bar
  Port 2222
```

However, on specific host I am deploying to the sshd is still running on 22.  I can connect fine using the ssh command (ssh -4 -p22 ...).  Using strace I see this line:

```
connect(3, {sa_family=AF_INET, sin_port=htons(22), sin_addr=inet_addr("xxx.xxx.xxx.xxx")}, 16) = 0
```

However when I try to do the same using guile-ssh:
```
$ guix shell guile guile-ssh strace -- strace guile -c '(use-modules (ssh session)) (define session (make-session #:host "pepe.foo.bar" #:user "root" #:log-verbosity '\''functions #:port 22)) (connect! session)' 2>&1 | grep htons
```

I see this instead:

```
connect(5, {sa_family=AF_INET, sin_port=htons(2222), sin_addr=inet_addr("xxx.xxx.xxx.xxx")}, 16) = 0
```

Notice that sin_port is set to the value from ~/.ssh/config instead of what I passed in #:port.

**Comment by artyom-poptsov** [comment]
Hello!

Thank you for the bug report.

I investigated the problem I came to conclusion that it's because currently the config file is being read after the options are set:
https://github.com/artyom-poptsov/guile-ssh/blob/7b2759753e875012aa18ece8aed39d9c89a44515/modules/ssh/session.scm#L110

So even though you provide `#:port` option to `make-session` and it set port it will be overwritten by the port number from the configuration file.

I think that we must read the config first and then set the provided options.

I'll see what I can do.

-avp

**Comment by artyom-poptsov** [comment]
As a workaround you can try to set the `#:config` option to `#f` so the configuration file will not be read:
https://github.com/artyom-poptsov/guile-ssh/blob/7b2759753e875012aa18ece8aed39d9c89a44515/modules/ssh/session.scm#L105

**Comment by artyom-poptsov** [comment]
As far as I can tell `process-config` and `#f` passed as the value for `config` option must have different meaning.  When `config` is set to `#f` it means that the default user configuration file (`~/.ssh/config`) must be read.  On the other hand, setting `process-config` (`SSH_OPTIONS_PROCESS_CONFIG`) to `#f` [means](https://api.libssh.org/stable/group__libssh__session.html#ga7a801b85800baa3f4e16f5b47db0a73d) that no configuration files should be read at all (including the system config):

> SSH_OPTIONS_PROCESS_CONFIG Set it to false to disable automatic processing of per-user and system-wide OpenSSH configuration files. LibSSH automatically uses these configuration files unless you provide it with this option or with different file (bool).

As such, having `process-config` option in Guile-SSH is desirable indeed, but I think that it does not solve the problem described in this issue.

But your attempt to solve the problem helped me to find another bug: currently there's no way to set config to `#f` in libssh as when `config` is false in `make-session` all the config handling code is skipped.  I'll fix it in the next release.

What is interesting with current situation is that when `config` option is set for `make-session` the configuration file should be read before setting other options thus options set after config is read should overwrite the options from the config.  But according to your observations we don't see this behavior.

**Comment by artyom-poptsov** [comment]
> Albeit that might be the intention, it is not obvious from the documentation:

Okay, that's a good point.  The documentation needs to be fixed.

But maybe we can improve the API as follows:
- `#:process-config #f` disables reading of any configuration files altogether as it works in libssh.
- `#:config "/dev/null"` or `#:config #f` means the same thing -- no user configuration file should be read.
- `#:config 'default` reads the default user configuration file (`~/.ssh/config`.)
- `#:config "/path/to/config"` specifies a config file to read.

What do you think?

> PS: The documentation snippet above still says

Yeah, it seems that was my intention back then when I implemented `make-session`.  But you're right, the options passed to `make-session` should overwrite the options from the config, it is more logical.

> should I open another bug?  I feel like I am spamming you enough already. :)

I think it's fine to use this bug to discuss the documentation changes related to `make-session` as well.  Thanks for helping!

BTW, I just fixed (d56fb10) a bug in a test that checks if options passed to `make-session` overwrite options from the user configuration.  The test looks now as follows:
```
(test-equal "make-session: keywords must overwrite config options"
  22
  (let ((s (make-session #:host   "example"
                         #:port   22
                         ;; Configuration sets port to 2222
                         #:config %config)))
    (session-get s 'port)))
```

The configuration file contains port number 2222 but `#:port` overwrites this value with 22 as it should so the test passes fine.

**Comment by artyom-poptsov** [comment]
Hello!  Sorry for the late answer.

> I guess for backward compatibility this needs to be default (no pun intended)
> value of #:config.  Do you think someone passes in #f explicitly in their code?

Agreed, we should keep backward compatibility where it's possible.  

But currently there's a problem in config-handling code in Guile-SSH:
1. Calling `%gssh-session-parse-config!` with `#f` in the place of the config tells libssh to read default configuration files.
2. In the meantime when config is set to `#f` in `make-session` then `%gssh-session-parse-config!` is not called at all, leading to some default internal libssh behavior.  So there's no way to call `%gssh-session-parse-config!` with `#f`.

So maybe we should go with the following:

- `#:config #f` means that no user configuration file should be read (as per Guile-SSH documentation.)  Internally we'll set `process-config?` option in libssh to `false`.  In the same time `#:config "/dev/null"` will be passed to libssh without any special handling as it works now.  Thus it would be a bugfix in the code so it will match the description in the documentation.
- `#:config #t` reads the default user configuration file (`~/.ssh/config`.)  We should use it by default for the backward compatibility.
- `#:config "/path/to/config"` specifies a config file to read (no changes in the API.)

That means that instead of
```scheme
    (when config
      (or host
          (throw 'guile-ssh-error
                 "'config' is specified, but 'host' option is missed."))
      (cond
       ((string? config)
        (%gssh-session-parse-config! session config))
       ((boolean? config)
        (%gssh-session-parse-config! session #f))
       (else
        (throw 'guile-ssh-error "Wrong 'config' value" config))))
```
we will do something like this (as you proposed):
```scheme
    (if config
        (begin
          (or host
              (throw 'guile-ssh-error
                     "'config' is specified, but 'host' option is missed."))
          (cond
           ((string? config)
            (%gssh-session-parse-config! session config))
           ((boolean? config)  ; set to #t
            (%gssh-session-parse-config! session #f))
           (else
            (throw 'guile-ssh-error "Wrong 'config' value" config))))
        (session-set! session 'process-config? #f))
```

Does this sound right?

By the way, I see that you've been quite active in Guile-SSH recently with several useful bug reports.  Do you want to participate in Guile-SSH development more directly?  You could start with a pull request to one of your issues, and then we'll see -- maybe I could give you the commit access.

Thanks!
-avp

**Comment by artyom-poptsov** [comment]
I pushed the proposed fix to the branch [38-the-port-seems-to-be-ignored](https://github.com/artyom-poptsov/guile-ssh/tree/38-the-port-seems-to-be-ignored).

-avp

**Comment by artyom-poptsov** [comment]
This issue should be fixed in the new Guile-SSH release.
