### ISSUE TITLE
Latest guile-ssh fails to build on armhf due to failed tests

### ISSUE THREAD

**Issue by ShiroiKuma0** [artyom-poptsov/guile-ssh#7]
I'm running an unmodified guix in Android on armhf phone - the guix armhf 0.14 binary build.

When trying to run guix pull it fails - due to guile-ssh build failing on failed tests - details at http://lists.gnu.org/archive/html/help-guix/2018-05/msg00066.html

**Comment by artyom-poptsov** [comment]
Hello,

unfortunately I don't have the right environment at the moment to test your case.  Could you please send me `tests/*.log` files from the project root directory after the test failure?  The logs may contain
some clues on the root cause of your test failures.

Thanks!

P.S.  I replied you in an email five days ago, but probably the email was not delivered or something.

**Comment by artyom-poptsov** [comment]
I fixed some test errors (see the `master` branch.)  Perhaps you should re-check build with the latest version of Guile-SSH.  If you do so and there will be any errors, please send me the logs.

Thanks.
